### ISSUE TITLE
Create_npy fail

### ISSUE THREAD

**Issue by Karltlbm** [VisualComputingInstitute/vkitti3D-dataset#1]
Hello

So i found your way to create an npy dataset from the raw one (which answers my issue : https://github.com/VisualComputingInstitute/3d-semantic-segmentation/issues/4#issue-466781813)

But, it just fails at some point. I tried 2 times, first time it got killed at 99%, the other time at 88%.
Anyway no directory is created.

![npy_fail](https://user-images.githubusercontent.com/49477491/61049743-8a060780-a3e5-11e9-8d1a-cf7278c91743.png)

**Comment by Karltlbm** [comment]
Is it something to do with the DeprecationWarning ? I tried to update pyparse, I use python 3.7 but still the problem remains.

**Comment by Karltlbm** [comment]
It finally worked ! 
All I have to do was not do anything during the process, my fragile laptop must have killed it every time...

**Comment by Joaovsky** [comment]
Hi @Karltlbm did you manage to execute the create_npy command without errors?

I get this error on debug: AttributeError: 'DataFrame' object has no attribute '_mgr'

And my full log when detecting the error is:

Program was launched with the following arguments:
~ root_path /home/mola/data/vkitti3D-dataset/datasets
~ out_path /home/mola/data/vkitti3D-dataset/datasets/vkitti_npy
~ bb_eps 0.3
~ cutoff 100.0
~ knn_eps 0.2
~ knn_number 1
~ sequence 0001
~ njobs 4
~ is_v1 False

Processing sequence 0001 ...

0.00it [00:00, ?it/s]
0it [00:00, ?it/s]
Traceback (most recent call last):
File "create_npy.py", line 462, in
main(args.root_path, args.out_path, args.bb_eps, args.cutoff, args.knn_eps,
File "create_npy.py", line 364, in main
overall_scene = np.vstack([output[i][0] for i in range(len(output))])
File "<array_function internals>", line 180, in vstack
File "/home/mola/miniconda3/envs/openmmlab/lib/python3.8/site-packages/numpy/core/shape_base.py", line 282, in vstack
return _nx.concatenate(arrs, 0)
File "<array_function internals>", line 180, in concatenate
ValueError: need at least one array to concatenate

Could you please tell me what I'm doing wrong? I have downloaded all the dataset folders they asked.

Thanks in advance!
