### ISSUE TITLE
Question about npy generation

### ISSUE THREAD

**Issue by phongnhhn92** [VisualComputingInstitute/vkitti3D-dataset#2]
Hello, I am curious about the process of generating numpy version of VKITTI dataset.
If I execute this command, then I  will have a numpy file which contains all RGB, depth, semantic, and XYZ position right ? 
`python create_npy.py --root_path path/to/root/vkitti_raw --out_path path/to/root/vkitti_npy --sequence 0001 --v2`
However, in the downloaded VKITTI folder, especially in the sequence 0001, there are 10 separate folders like this:
![image](https://user-images.githubusercontent.com/11288381/62619435-759f2700-b91f-11e9-918a-54b9d06a812a.png)
I wonder which version did this numpy file contains. When I try to read the code, seems like you guys create a list of image path in the "clone" folder. 
![image](https://user-images.githubusercontent.com/11288381/62619581-c878de80-b91f-11e9-9653-fcc81f393fd9.png)
But I can not find this "clone" folder, so I feel confused here. My purpose is to generate multiple numpy files for different conditions from the same sequence (0001 for example).
Thanks

**Comment by phongnhhn92** [comment]
Sorry I didnt see there is a "clone" folder :D

**Comment by Joaovsky** [comment]
Hi @phongnhhn92 did you manage to execute the command you put without errors?

I get this error on debug: AttributeError: 'DataFrame' object has no attribute '_mgr'

And my full log when detecting the error is:

Program was launched with the following arguments:
~ root_path /home/mola/data/vkitti3D-dataset/datasets
~ out_path /home/mola/data/vkitti3D-dataset/datasets/vkitti_npy
~ bb_eps 0.3
~ cutoff 100.0
~ knn_eps 0.2
~ knn_number 1
~ sequence 0001
~ njobs 4
~ is_v1 False

Processing sequence 0001 ...

0.00it [00:00, ?it/s]
0it [00:00, ?it/s]
Traceback (most recent call last):
File "create_npy.py", line 462, in
main(args.root_path, args.out_path, args.bb_eps, args.cutoff, args.knn_eps,
File "create_npy.py", line 364, in main
overall_scene = np.vstack([output[i][0] for i in range(len(output))])
File "<array_function internals>", line 180, in vstack
File "/home/mola/miniconda3/envs/openmmlab/lib/python3.8/site-packages/numpy/core/shape_base.py", line 282, in vstack
return _nx.concatenate(arrs, 0)
File "<array_function internals>", line 180, in concatenate
ValueError: need at least one array to concatenate

Could you please tell me what I'm doing wrong? I have downloaded all the dataset folders they asked.

Thanks in advance!
