### ISSUE TITLE
pre-trained weights + version of PointNet

### ISSUE THREAD

**Issue by ecapelli** [VisualComputingInstitute/vkitti3D-dataset#4]
Hi,

Thanks for making these tools and dataset available. 

Would it be possible to know which version of PointNet you compared to in your original paper ? Was it the basic version of pointnet, or the full version for segmentation ? And would you happen to have some weights for pointnet finetuned on vKITTI ?

Thanks in advance

Best regards

**Comment by francisengelmann** [comment]
Hi,

we used the PointNet version for segmentation (https://github.com/charlesq34/pointnet/tree/master/sem_seg).

We trained it from scratch on vKITTI. Let me know if you need more information.

Best Regards,
Francis

**Comment by ecapelli** [comment]
Ok, thanks for your quick answer !

Best regards
Edouard
